
CREATE TABLE IF NOT EXISTS `QuizQuestion` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,

    `quiz_id` INT NOT NULL REFERENCES `Quiz`(`id`),

    `question` VARCHAR(1023) NOT NULL,

    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);