CREATE TABLE IF NOT EXISTS `QuizAnswer` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,

    `question_id` INT NOT NULL REFERENCES `QuizQuestion`(`id`),

    `answer` VARCHAR(255) NOT NULL,
    `answer_index` INT NOT NULL,
    `is_correct` BOOLEAN NOT NULL,

    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);